---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  selector:
    app: frontend-d
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30021
#      targetPort: 80
#  externalIPs:
#    - 172.32.102.206
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-d
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-d
    spec:
      containers:

      - name: fe-httpd
        image: fe:1.0
        ports:
        - containerPort: 80